services:
  nextjs-app:
    build: .
    container_name: nextjs-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    networks:
      - nextjs-network
    command: npm run dev

networks:
  nextjs-network:
    driver: bridge
